repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
    - id: pyright

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
    - id: check-json5

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: cmake-lint
        require_serial: true
        name: lint
        entry: cmake -P cmake/lint.cmake
        language: system

  - repo: local
    hooks:
      - id: cmake-spell
        require_serial: true
        name: spell
        entry: cmake -DSPELL_COMMAND=./.venv/bin/codespell -P cmake/spell.cmake
        language: system
